version: '3'
services:
  mclojure:
    image: clojure
    hostname: mclojure
    container_name: mclojure
    volumes:
      - .:/app
    build:
      context: .
      dockerfile: Dockerfile-clojure
    command: lein run
    stdin_open: true
    tty: true
    ports:
      - "3449:3449"
    depends_on:
      - mpostgres
    links:
      - mpostgres
    environment:
      - MEASURE_HTTP_PORT=3000
      - MEASURE_DB_URL=jdbc:postgresql://mpostgres/mdb
      - MEASURE_DB_USER=muser
      - MEASURE_DB_PASSWORD=mpassword
  mnode:
    image: node
    hostname: mnode
    entrypoint: ./node-entrypoint.sh
    container_name: mnode
    working_dir: /app
    command: "npm run serve"
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    ports:
      - "8080:8080"
    links:
      - mclojure
  mpostgres:
    image: postgres:9.6
    hostname: mpostgres
    container_name: mpostgres
    environment:
      POSTGRES_USER: muser
      POSTGRES_PASSWORD: mpassword
      POSTGRES_DB: mdb
