version: '3'
services:
  mclojure:
    image: clojure:lein-2.8.1-alpine
    hostname: mclojure
    container_name: mclojure
    working_dir: /app
    volumes:
      - .:/app
    command: lein run
    stdin_open: true
    tty: true
    depends_on:
      - mpostgres
    links:
      - mpostgres
    environment:
      - MEASURE_HTTP_PORT=3000
      - MEASURE_DB_URL=jdbc:postgresql://mpostgres/mdb
      - MEASURE_DB_USER=muser
      - MEASURE_DB_PASSWORD=mpassword
  mnode:
    image: node:9.9.0-alpine
    hostname: mnode
    entrypoint: ./node-entrypoint.sh
    container_name: mnode
    working_dir: /app
    command: "npm run serve"
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    ports:
      - "8080:8080"
    links:
      - mclojure
  mpostgres:
    image: postgres:10.3-alpine
    hostname: mpostgres
    container_name: mpostgres
    environment:
      - POSTGRES_PASSWORD=mpassword
      - POSTGRES_USER=muser
      - POSTGRES_DB=mdb
